//! Deterministic, reviewable starter contracts for governed MCP workspaces.
//!
//! A contract is deliberately a static template, not an LLM-generated policy.
//! The caller supplies only its display name; every permission is visible in
//! the generated `kerna.toml` and must be changed by a human review.

use crate::config::BUNDLED_DEMO_SERVER;
use anyhow::{bail, Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

const DEPLOYMENT_ASSISTANT: &str = "deployment-assistant";

#[derive(Debug)]
pub struct ContractFiles {
    pub config: PathBuf,
    pub contract: PathBuf,
}

pub fn init(
    template: &str,
    name: &str,
    output: &Path,
    demo_server: bool,
) -> Result<ContractFiles> {
    if template != DEPLOYMENT_ASSISTANT {
        bail!(
            "Unknown contract template '{template}'. Available templates: {DEPLOYMENT_ASSISTANT}."
        );
    }

    let name = name.trim();
    if name.is_empty() {
        bail!("Contract name cannot be empty.");
    }
    if name.contains('\n') || name.contains('\r') {
        bail!("Contract name must be a single line.");
    }

    let config = output.join("kerna.toml");
    let contract = output.join("agent-contract.md");
    if config.exists() || contract.exists() {
        bail!(
            "Refusing to overwrite an existing contract in '{}'. Choose a new --output directory or review the files in place.",
            output.display()
        );
    }

    fs::create_dir_all(output).with_context(|| {
        format!(
            "Could not create contract directory '{}'.",
            output.display()
        )
    })?;
    fs::write(&config, deployment_toml(name, demo_server))
        .with_context(|| format!("Could not write '{}'.", config.display()))?;
    fs::write(&contract, deployment_contract(name))
        .with_context(|| format!("Could not write '{}'.", contract.display()))?;

    Ok(ContractFiles { config, contract })
}

fn toml_string(value: &str) -> String {
    toml::Value::String(value.to_owned()).to_string()
}

fn deployment_toml(name: &str, demo_server: bool) -> String {
    let quoted_name = toml_string(name);
    let server_block = if demo_server {
        format!(
            r#"
# The demo server that ships inside the Kerna binary. It exists so the policy
# boundary can be shown before any real connector exists: it needs no Docker,
# no image and no network. `runtime_mode = "demo"` is honoured for this one
# reserved name only, and the gateway ignores any command or image written
# here. Delete this block before adding a real plugin.
[[mcp_servers]]
name = "{BUNDLED_DEMO_SERVER}"
runtime_mode = "demo"
enabled = true
"#
        )
    } else {
        String::new()
    };
    format!(
        r#"# Kerna governed-MCP contract: {quoted_name}
# Generated by `kerna contract init`. Review every rule before use.
# This demo routes MCP tools only. It does not govern native IDE tools.

llm_provider = "mock"
llm_model = "mock"
db_path = "kerna.db"
sandbox_dir = "sandbox"
memory_backend = "sqlite"
runtime_mode = "docker"
network_mode = "none"
max_tool_calls = 10
max_llm_calls = 0
max_runtime_seconds = 120
max_output_bytes = 50000
max_memory_writes = 0
max_cost_usd = 0.0

# Add a reviewed, signed OCI plugin with:
# kerna mcp add <name> --image <image@sha256:...> --manifest <manifest.toml> \
#   --manifest-sha256 <sha256> --signing-public-key <base64-key> --read-root <path>
# Apart from the bundled demo server below, Kerna never launches a native MCP
# plugin from this contract.
{server_block}
# A harmless deterministic call for the Qoder demo.
[[permissions]]
tool = "echo"
action = "auto_approve"

# An intentionally unsafe request used to prove fail-closed governance.
[[permissions]]
tool = "network_probe"
action = "deny"

# Every other downstream MCP tool is denied unless a reviewer adds a rule.
[[permissions]]
tool = "*"
action = "deny"
"#,
    )
}

fn deployment_contract(name: &str) -> String {
    format!(
        r#"# Agent contract: {name}

## Purpose

This is a small, reviewable deployment-assistant starter contract for Kerna's
governed MCP gateway. It enables one server: the demo server bundled in the
Kerna binary, which exists only so the policy boundary can be seen before a
real connector exists. Replace it with a reviewed, signed OCI plugin before
governing real work.

## Scope

- Governed surface: MCP tools exposed through `kerna gateway`.
- Not governed in this contract: native Qoder, Claude Code, Codex, or other
  IDE tools that do not call the Kerna MCP server.
- Downstream server: the bundled demo server, or a pinned, signed OCI MCP image
  added through `kerna mcp add`. Native MCP launch is refused in production;
  the demo server is Kerna's own binary, not third-party code.

## Explicit policy

| Tool | Action | Reason |
| --- | --- | --- |
| `echo` | auto approve | Exposed by the bundled demo server. |
| `network_probe` | deny | Demonstrates a blocked network-adjacent request. |
| all other tools | deny | Fail closed until explicitly reviewed. |

## Budgets

- Maximum tool calls: 10
- Maximum runtime: 120 seconds
- Maximum output: 50,000 bytes
- No model calls, memory writes, or cost budget in this gateway-only demo.

## Review checklist

1. Read `kerna.toml`; do not treat this template as an approval.
2. Add a signed, digest-pinned OCI plugin using `kerna mcp add`.
3. Run `kerna doctor --gateway`; it must report the gateway ready.
4. Start `kerna gateway` from this directory and connect an MCP client.
5. Call `echo`, then call `network_probe`
   and confirm that Kerna returns an MCP error.
6. Inspect `kerna.db`/Kerna trace evidence before changing any allow rule.
"#,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn temp_output(label: &str) -> PathBuf {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!("kerna-contract-{label}-{nonce}"))
    }

    #[test]
    fn deployment_contract_is_valid_toml_and_fail_closed() {
        let output = temp_output("valid");
        let files = init(DEPLOYMENT_ASSISTANT, "Qoder demo", &output, true).unwrap();
        let config = fs::read_to_string(&files.config).unwrap();
        let parsed: toml::Value = toml::from_str(&config).unwrap();

        // The template's `echo`/`network_probe` rules are about tools that have
        // to come from somewhere. Without a server they name nothing, which is
        // how the documented demo came to be unrunnable.
        assert_eq!(
            parsed["mcp_servers"][0]["name"].as_str(),
            Some(BUNDLED_DEMO_SERVER)
        );
        assert_eq!(parsed["mcp_servers"][0]["runtime_mode"].as_str(), Some("demo"));
        assert_eq!(parsed["permissions"][0]["tool"].as_str(), Some("echo"));
        assert_eq!(
            parsed["permissions"][0]["action"].as_str(),
            Some("auto_approve")
        );
        assert_eq!(
            parsed["permissions"][1]["tool"].as_str(),
            Some("network_probe")
        );
        assert_eq!(parsed["permissions"][1]["action"].as_str(), Some("deny"));
        assert_eq!(parsed["permissions"][2]["tool"].as_str(), Some("*"));
        assert_eq!(parsed["permissions"][2]["action"].as_str(), Some("deny"));
        assert!(fs::read_to_string(&files.contract)
            .unwrap()
            .contains("Native MCP launch is refused"));

        let _ = fs::remove_dir_all(output);
    }

    #[test]
    fn no_demo_server_leaves_the_contract_without_one() {
        let output = temp_output("nodemo");
        let files = init(DEPLOYMENT_ASSISTANT, "Qoder demo", &output, false).unwrap();
        let parsed: toml::Value =
            toml::from_str(&fs::read_to_string(&files.config).unwrap()).unwrap();
        assert!(parsed.get("mcp_servers").is_none());
        let _ = fs::remove_dir_all(output);
    }

    #[test]
    fn refuses_to_overwrite_existing_contract() {
        let output = temp_output("overwrite");
        init(DEPLOYMENT_ASSISTANT, "Qoder demo", &output, true).unwrap();
        let error = init(DEPLOYMENT_ASSISTANT, "Other", &output, true).unwrap_err();
        assert!(error.to_string().contains("Refusing to overwrite"));
        let _ = fs::remove_dir_all(output);
    }

    #[test]
    fn rejects_unknown_template_and_invalid_name() {
        let output = temp_output("input");
        assert!(init("unknown", "Qoder demo", &output, true).is_err());
        assert!(init(DEPLOYMENT_ASSISTANT, "\n", &output, true).is_err());
    }
}
