name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: ./kernel
      
    - name: Check formatting
      run: cargo fmt -- --check
      working-directory: ./kernel
      
    - name: Run clippy
      run: cargo clippy -- -D warnings
      working-directory: ./kernel
      
    - name: Security audit
      uses: rustsec/audit-check@v1.4.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./kernel
